# Generated by Django 4.2.7 on 2023-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Name', models.CharField(max_length=50)),
                ('dispatch_date', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('lab_no', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('consultant', models.CharField(max_length=50)),
                ('investigation', models.CharField(max_length=50)),
                ('results', models.CharField(max_length=50)),
                ('reference_value', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
