# Generated by Django 4.2.7 on 2023-12-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_report_detail_test_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_detail',
            name='report',
        ),
    ]
