<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-23 16:40
=======
# Generated by Django 4.2.5 on 2023-12-24 02:20
>>>>>>> origin/ayushbhetwal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_report_detail_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_detail',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.report'),
        ),
    ]
