# Generated by Django 4.2.7 on 2023-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_techadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='techadd',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
