package swingexample;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Craze
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manage_Rooms = new javax.swing.JButton();
        Register = new javax.swing.JButton();
        Update_details = new javax.swing.JButton();
        Package = new javax.swing.JButton();
        Status = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to CloudBeds");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manage_Rooms.setBackground(new java.awt.Color(0, 153, 255));
        Manage_Rooms.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Manage_Rooms.setText("Manage Rooms");
        Manage_Rooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_RoomsActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        Register.setBackground(new java.awt.Color(0, 153, 255));
        Register.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Register.setText("Registration");
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 40));

        Update_details.setBackground(new java.awt.Color(0, 153, 255));
        Update_details.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Update_details.setText("Update Details");
        Update_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_detailsActionPerformed(evt);
            }
        });
        getContentPane().add(Update_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 130, 40));

        Package.setBackground(new java.awt.Color(0, 153, 255));
        Package.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Package.setText("Packages");
        getContentPane().add(Package, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 40));

        Status.setBackground(new java.awt.Color(0, 153, 255));
        Status.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 100, 40));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloudbeds-2.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_RoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_RoomsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Add_rooms s = new Add_rooms();
        s.setTitle("Add rooms");
        s.setVisible(true);
    }//GEN-LAST:event_Manage_RoomsActionPerformed

    private void Update_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_detailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Manage_Rooms;
    private javax.swing.JButton Package;
    private javax.swing.JButton Register;
    private javax.swing.JButton Status;
    private javax.swing.JButton Update_details;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
