# Generated by Django 4.2.7 on 2023-12-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_report_detail_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='dispatch_date',
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
