# Generated by Django 4.2.7 on 2023-12-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_report_dispatch_date_alter_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_detail',
            name='test_list',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
